import type { Metadata } from "next";
import { satoshi, integralCF } from "@/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${integralCF.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
