app = "shop-co-backend"
primary_region = "iad"

[build]

  dockerfile = "dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 1110
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    restart_limit = 0